name: virtualizarr-test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - codecov
  - h5netcdf
  - kerchunk==0.2.2
  - netcdf4
  - pydantic
  - pooch
  - pytest
  - pytest-cov
  - ruff
  - ujson
  - pip:
      - git+https://github.com/TomNicholas/xarray.git@concat-no-indexes#egg=xarray
